const { execFile, exec } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { v4: uuidv4 } = require('uuid');
const { fetchTranscriptAll } = require('../transcript_fetcher');

const YT_DLP_TIMEOUT = 30000;
const TRANSCRIPT_API_TIMEOUT = 20000;
const METADATA_TIMEOUT = 15000;

function validateYouTubeUrl(url) {
  const patterns = [
    /(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/|live\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/watch\?.*v=([a-zA-Z0-9_-]{11})/,
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}

function cleanTranscript(text) {
  if (!text) return '';
  let cleaned = text
    .replace(/\d{1,2}:\d{2}(:\d{2})?[,.]?\d*\s*--?>\s*\d{1,2}:\d{2}(:\d{2})?[,.]?\d*/g, '')
    .replace(/^\d+\s*$/gm, '')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\[\s*?\w+\s*?\]/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned;
}

function sanitizeTranscript(text) {
  if (!text) return '';
  if (text.length > 100000) {
    text = text.substring(0, 100000);
  }
  return text.replace(/[^\w\s\.\,\!\?\-\'\:\;\(\)\[\]\/\@\#\$\%\&\*]/g, ' ').trim();
}

function selectBestTranscript(results) {
  const enExact = results.find(r => r.lang === 'en' && !r.isAutoGenerated);
  if (enExact) return enExact;
  const enAuto = results.find(r => r.lang === 'en' && r.isAutoGenerated);
  if (enAuto) return enAuto;
  const anyManual = results.find(r => !r.isAutoGenerated);
  if (anyManual) return anyManual;
  return results[0];
}

async function extractUsingTranscriptApi(videoId, lang = 'en') {
  console.log('  [Method 1] Trying youtube-transcript API...');
  try {
    const result = await withTimeout(
      fetchTranscriptAll(videoId, lang),
      TRANSCRIPT_API_TIMEOUT,
      'YouTube transcript fetch'
    );
    if (result && result.fullText && result.fullText.length > 20) {
      console.log(`  [Method 1] Success: ${result.segments.length} segments (${result.fullText.length} chars)`);
      return {
        success: true,
        source: 'transcript-api',
        transcript: result.fullText,
        segments: result.segments,
      };
    }
    console.log('  [Method 1] Failed: empty or too short');
    return { success: false, source: 'transcript-api', error: 'Empty transcript' };
  } catch (e) {
    const msg = e.message || '';
    if (msg.includes('captcha') || msg.includes('too many requests') || msg.includes('429')) {
      console.log('  [Method 1] Failed: YouTube blocked (' + msg.substring(0, 80) + ')');
    } else {
      console.log('  [Method 1] Failed: ' + msg.substring(0, 80));
    }
    return { success: false, source: 'transcript-api', error: msg };
  }
}

function isYouTubeUrl(urlString) {
  try {
    const url = new URL(urlString);
    const hostname = url.hostname.toLowerCase();
    return ['youtube.com', 'www.youtube.com', 'youtu.be', 'm.youtube.com', 'music.youtube.com']
      .some(h => hostname === h || hostname.endsWith('.' + h));
  } catch {
    return false;
  }
}

async function extractUsingYtDlp(videoUrl) {
  console.log('  [Method 2] Trying yt-dlp...');
  if (!isYouTubeUrl(videoUrl)) {
    console.log('  [Method 2] Failed: URL not allowed');
    return { success: false, source: 'yt-dlp', error: 'URL not allowed' };
  }
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ytdlp-'));
  const outputTemplate = path.join(tmpDir, '%(id)s.%(ext)s');

  try {
    const videoId = validateYouTubeUrl(videoUrl);
    if (!videoId) {
      console.log('  [Method 2] Failed: Invalid YouTube URL');
      return { success: false, source: 'yt-dlp', error: 'Invalid YouTube URL' };
    }

    const subtitleFormats = [
      'vtt',
      'srt',
      'ttml',
    ];

    let subtitleFile = null;
    let transcriptText = null;

    for (const fmt of subtitleFormats) {
      try {
        const args = [
          '--write-subs',
          '--write-auto-subs',
          '--sub-langs', 'en',
          '--sub-format', fmt,
          '--skip-download',
          '--no-warnings',
          '--no-playlist',
          '--quiet',
          '-o', outputTemplate,
          videoUrl,
        ];

        try {
          await execFileWithTimeout('yt-dlp', args, YT_DLP_TIMEOUT);
        } catch (ytError) {
          continue;
        }

        const possibleFiles = [
          path.join(tmpDir, `${videoId}.en.${fmt}`),
          path.join(tmpDir, `${videoId}.en-US.${fmt}`),
          path.join(tmpDir, `${videoId}.en-GB.${fmt}`),
        ];

        for (const pf of possibleFiles) {
          if (fs.existsSync(pf)) {
            subtitleFile = pf;
            break;
          }
        }

        if (subtitleFile && fs.existsSync(subtitleFile)) {
          const raw = fs.readFileSync(subtitleFile, 'utf8');
          const cleaned = cleanTranscript(raw);
          if (cleaned && cleaned.length > 20) {
            transcriptText = cleaned;
            break;
          }
        }
      } catch (e) {
        continue;
      }
    }

    if (!transcriptText) {
      try {
        const allArgs = [
          '--write-subs',
          '--write-auto-subs',
          '--sub-langs', 'all',
          '--sub-format', 'vtt/srt/ttml',
          '--skip-download',
          '--no-warnings',
          '--no-playlist',
          '--quiet',
          '-o', outputTemplate,
          videoUrl,
        ];
        try {
          await execFileWithTimeout('yt-dlp', allArgs, YT_DLP_TIMEOUT);
        } catch (e) {}

        const dirFiles = fs.readdirSync(tmpDir);
        const subFile = dirFiles.find(f =>
          (f.endsWith('.vtt') || f.endsWith('.srt') || f.endsWith('.ttml')) &&
          !f.includes(videoId + '.')
        );
        if (subFile) {
          const subPath = path.join(tmpDir, subFile);
          const raw = fs.readFileSync(subPath, 'utf8');
          const cleaned = cleanTranscript(raw);
          if (cleaned && cleaned.length > 20) {
            transcriptText = cleaned;
          }
        }
      } catch (e) {}
    }

    cleanupTmpDir(tmpDir);

    if (transcriptText) {
      console.log(`  [Method 2] Success: ${transcriptText.length} chars extracted`);
      return {
        success: true,
        source: 'yt-dlp',
        transcript: transcriptText,
        segments: [{ text: transcriptText, offset: 0, duration: 0 }],
      };
    }

    console.log('  [Method 2] Failed: No subtitles found');
    return { success: false, source: 'yt-dlp', error: 'No subtitles found via yt-dlp' };
  } catch (e) {
    cleanupTmpDir(tmpDir);
    const msg = e.message || '';
    if (msg.includes('not recognized') || msg.includes('ENOENT') || msg.includes('not found')) {
      console.log('  [Method 2] Failed: yt-dlp not installed');
    } else {
      console.log('  [Method 2] Failed: ' + msg.substring(0, 80));
    }
    return { success: false, source: 'yt-dlp', error: msg };
  }
}

async function extractMetadata(videoUrl) {
  console.log('  [Method 3] Trying metadata extraction...');

  const videoId = validateYouTubeUrl(videoUrl);
  if (!videoId) {
    console.log('  [Method 3] Failed: Invalid YouTube URL');
    return { success: false, source: 'metadata', error: 'Invalid YouTube URL' };
  }

  const metadata = {
    title: 'YouTube Video',
    description: '',
    channel_name: '',
    upload_date: '',
    duration: 0,
    thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    video_id: videoId,
  };

  const youtubeApiKey = process.env.YOUTUBE_API_KEY;

  if (youtubeApiKey) {
    try {
      console.log('  [Method 3] Using YouTube Data API...');
      const resp = await withTimeout(
        fetch(`https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=${videoId}&key=${youtubeApiKey}`),
        METADATA_TIMEOUT,
        'YouTube Data API'
      );
      if (resp.ok) {
        const data = await resp.json();
        if (data.items && data.items[0]) {
          const snippet = data.items[0].snippet;
          const contentDetails = data.items[0].contentDetails;
          metadata.title = snippet.title || metadata.title;
          metadata.description = snippet.description || '';
          metadata.channel_name = snippet.channelTitle || '';
          metadata.upload_date = snippet.publishedAt || '';
          if (contentDetails && contentDetails.duration) {
            const match = contentDetails.duration.match(/PT(\d+H)?(\d+M)?(\d+S)?/);
            if (match) {
              const hours = parseInt(match[1]) || 0;
              const minutes = parseInt(match[2]) || 0;
              const seconds = parseInt(match[3]) || 0;
              metadata.duration = hours * 3600 + minutes * 60 + seconds;
            }
          }
          const thumbs = snippet.thumbnails || {};
          const bestThumb = thumbs.maxres || thumbs.high || thumbs.medium || thumbs.default;
          if (bestThumb && bestThumb.url) {
            metadata.thumbnail_url = bestThumb.url;
          }
          console.log('  [Method 3] Success: metadata via YouTube Data API');
          return { success: true, source: 'metadata', metadata };
        }
      }
      console.log('  [Method 3] YouTube Data API returned no items');
    } catch (e) {
      console.log('  [Method 3] YouTube Data API failed: ' + (e.message || '').substring(0, 80));
    }
  } else {
    console.log('  [Method 3] No YOUTUBE_API_KEY, trying yt-dlp for metadata...');
  }

  try {
    if (!isYouTubeUrl(videoUrl)) {
      console.log('  [Method 3] Failed: URL not allowed');
      return { success: false, source: 'metadata', error: 'URL not allowed' };
    }
    console.log('  [Method 3] Using yt-dlp for metadata...');
    const result = await execFileWithTimeout('yt-dlp', [
      '--dump-json',
      '--no-warnings',
      '--no-playlist',
      '--quiet',
      videoUrl,
    ], METADATA_TIMEOUT);

    if (result && result.stdout) {
      const data = JSON.parse(result.stdout.trim().split('\n')[0]);
      metadata.title = data.title || metadata.title;
      metadata.description = data.description || '';
      metadata.channel_name = data.channel || data.uploader || '';
      metadata.upload_date = data.upload_date || '';
      metadata.duration = data.duration || 0;
      if (data.thumbnail) metadata.thumbnail_url = data.thumbnail;
      console.log('  [Method 3] Success: metadata via yt-dlp');
      return { success: true, source: 'metadata', metadata };
    }
  } catch (e) {
    const msg = e.message || '';
    if (msg.includes('not recognized') || msg.includes('ENOENT') || msg.includes('not found')) {
      console.log('  [Method 3] yt-dlp not installed for metadata fallback');
    } else {
      console.log('  [Method 3] yt-dlp metadata failed: ' + msg.substring(0, 80));
    }
  }

  console.log('  [Method 3] Returning fallback metadata');
  return { success: true, source: 'metadata-fallback', metadata };
}

function parseVttToPlainText(vttContent) {
  return vttContent
    .replace(/WEBVTT[\s\S]*?(\d{2}:\d{2})/, '$1')
    .split(/\n\s*\n/)
    .map(block => {
      const lines = block.trim().split('\n');
      const textLines = lines.filter(line => {
        const trimmed = line.trim();
        if (!trimmed) return false;
        if (/^\d{1,2}:\d{2}(:\d{2})?[,.]?\d*\s*--?>\s*\d{1,2}:\d{2}(:\d{2})?[,.]?\d*$/.test(trimmed)) return false;
        if (/^\d+$/.test(trimmed)) return false;
        if (trimmed.startsWith('NOTE')) return false;
        if (/^<c[.\s>]/.test(trimmed)) return false;
        return true;
      });
      return textLines.join(' ');
    })
    .filter(b => b.trim().length > 0)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseSrtToPlainText(srtContent) {
  return srtContent
    .split(/\n\s*\n/)
    .map(block => {
      const lines = block.trim().split('\n');
      const textLines = lines.filter((line, index) => {
        const trimmed = line.trim();
        if (!trimmed) return false;
        if (/^\d+$/.test(trimmed) && index === 0) return false;
        if (/\d{2}:\d{2}:\d{2}[,.]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[,.]\d{3}/.test(trimmed)) return false;
        return true;
      });
      return textLines.join(' ');
    })
    .filter(b => b.trim().length > 0)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseTtmlToPlainText(ttmlContent) {
  return ttmlContent
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseSubtitleFile(filePath) {
  if (!fs.existsSync(filePath)) return null;
  const content = fs.readFileSync(filePath, 'utf8');
  const ext = path.extname(filePath).toLowerCase();

  if (ext === '.vtt') return parseVttToPlainText(content);
  if (ext === '.srt') return parseSrtToPlainText(content);
  if (ext === '.ttml' || ext === '.xml') return parseTtmlToPlainText(content);

  return cleanTranscript(content);
}

async function getTranscriptWithRetries(videoUrl, lang = 'en') {
  const videoId = validateYouTubeUrl(videoUrl);
  if (!videoId) {
    return { success: false, error: 'Invalid YouTube URL', errorCode: 'INVALID_URL' };
  }

  console.log(`\n  ╔══════════════════════════════════════════╗`);
  console.log(`  ║   Transcript Extraction Pipeline         ║`);
  console.log(`  ║   Video ID: ${videoId.padEnd(36)}║`);
  console.log(`  ╚══════════════════════════════════════════╝`);

  let stepResult;

  stepResult = await extractUsingTranscriptApi(videoId, lang);
  if (stepResult.success) {
    console.log(`  ──▶ Using transcript from: ${stepResult.source}`);
    return {
      success: true,
      transcript: sanitizeTranscript(stepResult.transcript),
      segments: stepResult.segments || [],
      source: stepResult.source,
    };
  }
  console.log(`  ──▶ Failed, moving to next method...`);

  stepResult = await extractUsingYtDlp(videoUrl);
  if (stepResult.success) {
    console.log(`  ──▶ Using transcript from: ${stepResult.source}`);
    const sanitized = sanitizeTranscript(stepResult.transcript);
    return {
      success: true,
      transcript: sanitized,
      segments: [{ text: sanitized, offset: 0, duration: 0 }],
      source: stepResult.source,
    };
  }
  console.log(`  ──▶ Failed, moving to next method...`);

  const metadataResult = await extractMetadata(videoUrl);
  if (metadataResult.success) {
    console.log(`  ──▶ Using metadata from: ${metadataResult.source}`);
    return {
      success: true,
      transcript: null,
      segments: [],
      source: 'metadata',
      metadata: metadataResult.metadata,
      transcriptUnavailable: true,
      analysisNote: 'Transcript unavailable. Analysis based on available metadata only.',
    };
  }
  console.log(`  ──▶ All automatic methods failed. Manual transcript required.`);

  return {
    success: false,
    error: 'Could not extract captions from this video. YouTube may be blocking automated caption access or the video may not have captions.',
    errorCode: 'TRANSCRIPT_UNAVAILABLE',
    suggestion: 'Please paste the video transcript manually or try another video.',
    source: null,
  };
}

function execFileWithTimeout(cmd, args, timeoutMs) {
  return new Promise((resolve, reject) => {
    const proc = execFile(cmd, args, { timeout: timeoutMs, maxBuffer: 10 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) {
        reject(err);
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

function withTimeout(promise, ms, label = 'operation') {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms)
    )
  ]);
}

function cleanupTmpDir(dirPath) {
  try {
    if (fs.existsSync(dirPath)) {
      const files = fs.readdirSync(dirPath);
      for (const file of files) {
        fs.unlinkSync(path.join(dirPath, file));
      }
      fs.rmdirSync(dirPath);
    }
  } catch (e) {}
}

module.exports = {
  getTranscriptWithRetries,
  extractUsingTranscriptApi,
  extractUsingYtDlp,
  extractMetadata,
  cleanTranscript,
  sanitizeTranscript,
  selectBestTranscript,
  validateYouTubeUrl,
};
